services:
  postgres:
    image: postgres:15
    container_name: spectra_postgres
    environment:
      POSTGRES_USER: spectra  # Application user (default user created by init)
      POSTGRES_PASSWORD: REPLACE-ME  # Password for the application user
      POSTGRES_DB: spectraiim  # Default database created at init
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
