services:
  postgres:
    image: postgres:latest
    container_name: spectra_postgres
    environment:
      POSTGRES_USER: spectra
      POSTGRES_PASSWORD: spectra_password
      POSTGRES_DB: spectraiim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spectra -d spectraiim"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitor:
    image: ghcr.io/paul1404/spectraiim:latest
    container_name: spectra_monitor
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_NAME: spectraiim
      DB_USER: spectra
      DB_PASSWORD: spectra_password
      DB_HOST: postgres
      DB_PORT: 5432
      PING_TARGET: 1.1.1.1
      DNS_TEST_DOMAIN: one.one.one.one
      PING_INTERVAL: 60
      SPEEDTEST_INTERVAL: 1800
      LOG_LEVEL: INFO
    cap_add:
      - NET_RAW
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: spectra_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data: