apiVersion: 1
datasources:
  - name: Spectraiim
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    uid: spectraiim-influxdb
    jsonData:
      version: Flux
      organization: spectra_org
      defaultBucket: network_logs
      tlsSkipVerify: true
    secureJsonData:
      token: spectra_token